accounts/urls.py
from django.conf.urls import url


from . import views

app_name="accounts"

urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/edit/$', views.profile_edit, name='profile_edit'),
]

alosman/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('contact/', include('contact.urls', namespace='contact')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('home/', include('products.urls', namespace='home')),
    path('products/', include('products.urls', namespace='products')),
    path('transactions/', include('products.urls', namespace='transactions')),
    path(r'api-auth/', include('rest_framework.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url
from django.urls import path


from . import views
from . import api

app_name="products"

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^products/$', views.all_products, name="all_products"), #This name will be used in templates in url
    url(r'^(?P<code>[a-zA-Z0-9]+)/$', views.product, name="product"),
    url(r'^add_product/$', views.add_product, name="add_product"),
    url(r'^(?P<code>[a-zA-Z0-9]+)/edit_product/$', views.edit_product, name="edit_product"),
    url(r'^add_transactions/$', views.add_transactions, name="add_transactions"),
    url(r'^add_transaction/$', views.add_transaction, name="add_transaction"),
    
    #api 
    path('api/products', api.product_list_api, name="product_list_api"),
    path('api/products/<code>', api.product_detail_api, name="product_detail_api"),
    
    #class Based Views
    path('api/v2/products', api.ProductListAPI.as_view(), name="ProductListAPI"),
    path('api/v2/products/<code>', api.ProductDetailAPI.as_view(), name="ProductDetailAPI"),

]

products/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid






# Create your models here.

class Product(models.Model):
    code = models.CharField(max_length=50, primary_key=True)
    name = models.CharField(max_length=50, unique=True, default="defaultName")
    model = models.CharField(max_length=50, default="product")
    cost = models.IntegerField()
    selling_price = models.IntegerField()
    size = models.CharField(max_length=10)
    img = models.ImageField(upload_to="product_img/", default="product_img/default.png")
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class Supplier(models.Model):
    name = models.CharField(max_length=50, unique=True)
    telephone_number = models.IntegerField()

    def __str__(self):
        return self.name



class AddTransaction(models.Model):
    date = models.DateField(auto_now=False, auto_now_add=False)
    product_code = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product_code", to_field="code", db_column="code", default="code")
    quantity = models.IntegerField()
    
    def __str__(self):
        return self.product_code.name

products/forms.py
from django import forms
from .models import Product, AddTransaction




class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['code','name', 'cost','selling_price', 'size', 'img']
        widgets = {
            'code': forms.TextInput(attrs={'readonly': 'readonly'})
        }
     
class AddTransactionForm(forms.ModelForm):
    class Meta:
        model = AddTransaction
        fields = ['date', 'product_code', 'quantity']
        
    

        

products/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
# Create your views here.

from .models import Product
from .forms import ProductForm, AddTransactionForm


def home(request):
    return render(request, "home.html")


#return all products
@login_required
def all_products(request):
    all_products = Product.objects.filter(active=True)

    context = {
        "all_products": all_products
    }

    return render(request, 'all_products.html', context)

#return one product by id
def product(request, code):
    product = get_object_or_404(Product, code=code)

    context = {
        "product": product
    }

    return render(request, 'product.html', context)



def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST) #if form.is_valid():
        #new_form = form.save(commit=False)
        #new_form.user = request.user
        form.save()
        return redirect('/products')

    else:
        form = ProductForm()

    context = {
        "form": form
    }

    return render(request, "add_product.html", context)


def edit_product(request, code):
    product = get_object_or_404(Product, code=code)
    #The if part is executed after we press submit
    if request.method == 'POST':
        form = ProductForm(request.POST, instance=product) #if form.is_valid():
        #new_form = form.save(commit=False)
        #new_form.user = request.user
        form.save()
        return redirect('/products')
    #The else part is executed before we press submit
    else:
        form = ProductForm(instance=product)

    context = {
        "form": form,
    }

    return render(request, "edit_product.html", context)



def add_transactions(request):
    return render(request, "transactions.html")


def add_transaction(request):
    if request.method == 'POST':
        form = AddTransactionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/products/add_transactions')
    else:
        form = AddTransactionForm()
        
    context = {
        "form": form
    }
    return render(request, "add_transaction.html", context)

products/templates/add_product.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block body %}

<div class="container">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}

      <button class="btn btn-primary">Submit</button>


    </form>

</div>    
    
{% endblock %}

products/templates/add_transaction.html
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}

  <button class="btn btn-primary">Submit</button>


</form>

products/templates/all_products.html
{% extends "base.html" %}

<a href="{% url 'products:add_product' %}">
  <button class="btn btn-successful">Add Product</button>
</a>







{% block body %}
<!-- PRODUCTS CARDS -->

<div class=container>
  <div class="row mt-4">

    <!-- Loop on Cards -->
    {% for product in all_products %}
      <div class="col-md-4">
        <div class="card card-adjust">
          {% if product.img %}
          <img class="card-img-top img-adjust" src="{{product.img.url}}" alt="Card image cap">
          {% endif %}
          <div class="card-body">
            <h5 class="card-title card-title-adjust">{{product.name}}</h5>
            <div class="h5andspan"><h5 class="h5-adjust">Model: </h5> <span>{{product.model}}</span></div>
            <div class="h5andspan"><h5 class="h5-adjust">Price: </h5> <span>{{product.selling_price}}</span></div>
            <a href="{% url 'products:product' product.code %}" class="btn btn-primary">Know more</a>
          </div>
        </div>
      </div>
      {% endfor %}


  </div>
</div>

{% endblock body %}

<!-- END PRODUCTS CARDS -->

products/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home_static/css/style.css' %}">
    <title>Al-Osman</title>
  </head>
  <body>
<!-- NAVBAR START -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Al-Osman</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'products:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'products:all_products' %}">Products</a>
      </li>
      

    </ul>
      {% if request.user.is_authenticated %}
      
        <ul class="navbar-nav new-list pull-right">
            <li class="nav-item pull-right">
            <a class="nav-link" href="{% url 'accounts:profile' %}">Profile</a>
            </li>
        </ul>  
      {% else %}
        <ul class="navbar-nav new-list pull-right">
            <li class="nav-item pull-right">
            <a class="nav-link" href="{% url 'login' %}">Log In</a>
            </li>
        </ul>  
      {% endif %}
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
      

<!-- NAVBAR END -->


{% block body %}
{% endblock body %}


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

products/templates/edit_product.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block body %}

<div class="container">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}

      <button class="btn btn-primary">Submit</button>


    </form>
</div>

{% endblock %}

products/templates/home.html
{% extends "base.html" %}


{% block body %}
<div class="container mt-4">


  <div class="row">

      <div class="col-md-4">
        <a href="{% url 'products:all_products' %}"><button class="btn btn-primary">Products</button></a>
      </div>


      <div class="col-md-4">
        <a href="{% url 'products:add_product' %}"><button class="btn btn-primary">Add Product</button></a>
      </div>


      <div class="col-md-4">
        <button class="btn btn-primary">Empty</button>
      </div>




  </div>

</div>
{% endblock body %}

products/templates/product.html
{% extends "base.html" %}
{% load static %}



{% block body %}
<!-- PRODUCTS CARDS -->

<div class=container>
  <div class="row mt-4">

    <!-- First Card -->
      <div class="col-md-4">
        <div class="card card-adjust">
          {% if product.img %}
          <img class="card-img-top img-adjust" src="{{product.img.url}}" alt="Card image cap">
          {% endif %}
          <div class="card-body mx-auto">
            <h5 class="card-title card-title-adjust">{{product.name}}</h5>
            <div class="h5andspan"><h5 class="h5-adjust">Model: </h5> <span>{{product.model}}</span></div>
            <div class="h5andspan"><h5 class="h5-adjust">Price: </h5> <span>{{product.selling_price}}</span></div>
          </div>
        </div>
      </div>


  </div>

<div>
<a href="{% url 'products:edit_product' product.code %}">Edit Product</a>    
</div>

</div>

{% endblock body %}

<!-- END PRODUCTS CARDS -->

products/templates/transactions.html
{% load static %}
<!DOCTYPE html>


<html>
    <head>
        <title>Add Transactions</title>
        <link rel="stylesheet" type="text/css" href="{% static 'products/css/bootstrap.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'products/css/mystyle.css' %}">
    </head>
    
    <body>
        <h1 class="text-center my-heading">Add Transactions</h1>
        
        
            <div class="container my-container">
              

                <div class="col-md-3">
                    <a href="{% url 'products:add_transaction' %}">
                        <button class="btn btn-primary">New Transaction</button>
                    </a>
                </div>
                <div class="col-md-3">
                    <a>
                        <button class="btn btn-primary">Print Transaction</button>
                    </a>
                </div>
                <div class="col-md-3">
                    <a>
                        <button class="btn btn-primary">Edit Transaction</button>
                    </a>
                </div>
                <div class="col-md-3">
                    <a>
                        <button class="btn btn-primary">Search</button>
                    </a>
                </div>
            </div>
        
    
    
    </body>



</html>